name: Pulumi Deploy

on: 
    workflow_dispatch:
    pull_request:
        branches: [main]  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pulumi pulumi-aws

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS}}
          aws-secret-access-key: ${{ secrets.AWS_SEC }}
          aws-region: us-west-2  # Replace with your region

      - name: Set up Pulumi
        uses: pulumi/actions@v5
        with:
          command: up
          stack-name: dev  # Specify your Pulumi stack name here
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_KEY }}

      - name: Pulumi Output
        run: pulumi stack output