name: Pulumi Destroy
on: 
  workflow_dispatch:
    
jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      PULUMI_STACK: ${{secrets.PULUMI_STACK}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Install Pulumi SDK
        run: | 
          pip install pulumi
          pip install pulumi pulumi-aws
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS}}
          aws-secret-access-key: ${{ secrets.AWS_SEC }}
          aws-region: us-west-2  # Replace with your region

      - name: Set up Pulumi
        uses: pulumi/actions@v5
        with:
          command: destroy
          stack-name: ${{ env.PULUMI_STACK }}  # Specify your Pulumi stack name here
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_KEY }}

      - name: Pulumi Output
        run: pulumi stack output